apps/courses/urls.py
from django.urls import path

from apps.courses import views


urlpatterns = [
    path('', views.CourseIndexView.as_view(), name='list'),
    path('<int:pk>/', views.CourseDetailView.as_view(), name='detail'),
    path('<int:course_id>/learn', views.CourseStudyView.as_view(),
         name='learn'),
]

apps/operations/urls.py
from django.urls import path

from apps.operations import views


urlpatterns = [
    path('fav/', views.FavoriteView.as_view(), name='fav'),
]

apps/organizations/urls.py
from django.urls import path

from apps.organizations import views


urlpatterns = [
    path('', views.OrgIndexView.as_view(), name='list'),
    path('<int:org_id>/', views.OrgDescView.as_view(), name='desc'),
    path('<int:org_id>/teachers/', views.OrgTeacherView.as_view(),
         name='teachers'),
    path('<int:org_id>/courses/', views.OrgCourseView.as_view(),
         name='courses'),
    # path('<int:org_id>/desc/', views.OrgDescView.as_view(),
    #      name='desc'),
]

edu_online/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, re_path
from django.views.generic import TemplateView
from django.views.static import serve

from apps.users.views import LoginView, LogoutView
from edu_online.settings import MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('captcha/', include('captcha.urls')),
    path('org/', include(('apps.organizations.urls', 'organizations'),
                         namespace='org')),
    path('op/', include(('apps.operations.urls', 'operations'),
                        namespace='op')),
    path('course/', include(('apps.courses.urls', 'courses'),
                            namespace='course')),
    # 配置上传文件的访问url
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
]

templates/base.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}首页 - 慕学在线网{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block custom_css %}
    {% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type=text/javascript></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type=text/javascript></script>

</head>
<body>
<section class="headerwrap ">
    <header>
		<div  class=" header">
 			<div class="top">
				<div class="wp">
					<div class="fl"><p>服务电话：<b>33333333</b></p></div>
					{% if request.user.is_authenticated %}
                        <!--登录后跳转-->
                        <div class="personal">
                            <dl class="user fr">
                                <dd>{{ request.user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20" src="{% static 'media/image/2016/12/default_big_14.png' %}"/></dt>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                    <dt><img width="80" height="80" src="{% static 'media/image/2016/12/default_big_14.png' %}"/></dt>
                                    <dd>
                                        <h2>django</h2>
                                        <p>bobby</p>
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="usercenter-info.html">进入个人中心</a>
                                    <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <a style="color:white" class="fr registerbtn" href="register.html">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                    {% endif %}
				</div>
			</div>

            <div class="middle">
                <div class="wp">
                    <a href="{% url 'index' %}"><img class="fl" src="{% static 'images/wanderingearth.png' %}"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程机构</li>
                                <li data-value="teacher">授课老师</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
                    </div>
                </div>
            </div>


			<nav>
				<div class="nav">
					<div class="wp">
						<ul>
							<li class="{% if request.path == '/' %}active{% endif %}"><a href="{% url 'index' %}">首页</a></li>
							<li class="{% if request.path|slice:'7' == '/course' %}active{% endif %}">
								<a href="{% url 'course:list' %}">
									公开课<img class="hot" src="{% static 'images/nav_hot.png' %}">
								</a>
							</li>
							<li >
								<a href="teachers-list.html">授课教师</a>
							</li>
							<li class="{% if request.path|slice:'4' == '/org' %}active{% endif %}"><a href="{% url 'org:list' %}">授课机构</a></li>
						</ul>
					</div>
				</div>
			</nav>

			</div>
    </header>
</section>
<!--crumbs start-->

{% block custom_bread %}
{% endblock %}

{% block content %}
{% endblock %}

<footer>
		<div class="footer">
			<div class="wp">
				<ul class="cont">
					<li class="logo"><a href=""><img src="{% static 'images/footlogo.png' %}"/></a></li>
					<li class="code"><img src="{% static 'images/code.jpg' %}"/><p class=center>扫描关注微信</p></li>
					<li class="third"><img class="fl" src="{% static 'images/tell.png' %}"/><p class=tell>33333333</p><p class=time>周一至周日 9:00-18:00</p></li>
				</ul>

			</div>
			<p class="line"></p>
			<div class="wp clear">
                <span class="fl">? 2016 www.projectsedu.com 慕学在线-在线学习交流平台 保留所有权利</span>
                <span class="fr">copyright ? 2016 ICP备案证书号：蜀ICP备xxxxx号-1</span>
			</div>
		</div>
	</footer>

<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type=text/javascript></script>
<script src="{% static 'js/unslider.js' %}" type=text/javascript></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type=text/javascript></script>
<script src="{% static 'js/deco-common.js' %}"  type=text/javascript></script>
{% block custom_js %}
{% endblock %}

</body>
</html>

templates/org_base.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    <link rel="stylesheet" href="{% static 'css/message.min.css' %}">
    {% block custom_css %}
    {% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type=text/javascript></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type=text/javascript></script>

</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
		<div  class="header2 header">

            <div class="top">
				<div class="wp">
					<div class="fl">
                        <p>联系方式：<b>3333333333</b></p>
                    </div>
                    {% if request.user.is_authenticated %}
                        <!--登录后跳转-->
                        <div class="personal">
                            <dl class="user fr">
                                <dd>{{ request.user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20" src="{% static 'media/image/2016/12/default_big_14.png' %}"/></dt>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                    <dt><img width="80" height="80" src="{% static 'media/image/2016/12/default_big_14.png' %}"/></dt>
                                    <dd>
                                        <h2>django</h2>
                                        <p>bobby</p>
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="usercenter-info.html">进入个人中心</a>
                                    <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <a style="color:white" class="fr registerbtn" href="register.html">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                    {% endif %}
				</div>
			</div>


            <div class="middle companyheader">
                <div class="wp">
                    <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ org.avatar }}"/>
                    <div class="head fl">
                        <h1>
                            {{ org.name }}
                            {% if org.is_certified %}
                                <img src="{% static 'images/authentication.png' %}"/>
                            {% endif %}
                            {% if org.is_gold %}
                                <img src="{% static 'images/gold.png' %}"/>
                            {% endif %}
                        </h1>
                        <p class="fl">
                            <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                            <span class="precision company-credit" data-star-scope="5.0"></span>
                            <span class="key">5.0</span>
                        </p>
                    </div>
                    <div id="collect" class="btn fr collectionbtn notlogin" data-favid="22" data-fav-type="1">
                        {% if favorite %}
                            取消收藏
                        {% else %}
                            收藏
                        {% endif %}
                    </div>

                </div>
            </div>
        </div>
    </header>
</section>
<section>
	<div class="wp">
		<ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
			<li><a href="{% url 'org:list' %}">机构</a>></li>
			<li>{% block org_bread_path %}{% endblock %}</li>
		</ul>
	</div>
</section>

<section>
	<div class="wp list personal_list comp">
		<div class="left">
			<ul>
				<li class="{% if page_title == 'desc' %}active2{% endif %}"><a href="{% url 'org:desc' org.id %}">机构首页</a></li>
                <li class="{% if page_title == 'course' %}active2{% endif %}"><a href="{% url 'org:courses' org.id %}">机构课程</a></li>
<!--                <li class="{% if page_title == 'desc' %}active2{% endif %}"><a href="{% url 'org:desc' org.id %}">机构介绍</a></li>-->
                <li class="{% if page_title == 'teacher' %}active2{% endif %}"><a href="{% url 'org:teachers' org.id %}">机构讲师</a></li>
			</ul>
		</div>
        {% block org_right_layout %}
        {% endblock %}
    </div>
</section>
<!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<!--sidebar end-->
<!--header start-->

<!--弹出省省市-->
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type=text/javascript></script>

<script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type=text/javascript></script>
<script src="{% static 'js/deco-common.js' %}"  type=text/javascript></script>
<script src="{% static 'js/message.min.js' %}"></script>

{% block custom_js %}
{% endblock %}
<script type="text/javascript">
//收藏分享
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"{% url 'op:fav' %}",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="{% url 'login' %}";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                //current_elem.text(data.msg)
                //$("#collect").load(location.href + " #collect>*", "");
                window.location.reload(true)
            }
        },
    });
}

$(document).ready(function() {
    $('.collectionbtn').on('click', function () {
        add_fav($(this), {{ org.id }}, 3);
    });
});

$(function(){
    var $precision = $('.precision'),
        score = $precision.attr('data-star-scope'),
        option =  {
                    half		: true,
                    path		: '{% static 'images/' %}',
                    precision	: true,
                    size		: 24,
                    starOff		: 'g_star.png',
                    starOn		: 'r_star.png',
                    starHalf	: 'h_star.png',
                    hints       : ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg  : '暂时还未获得评价！',
                    readOnly    : true,
                    score       : score
                };
    $precision.raty(option);

    $(document).ready(function() {
        $('.jsFavBtn').on('click', function () {
            var type = $(this).attr('data-fav-type');
            if (type == '1') {
                favPraise($(this), 'fav', 1, '收藏');

            } else if (type == '3') {
                favPraise($(this), 'fav', 3);

            } else if (type == '11') {
                favPraise($(this), 'pra', 1);

            } else if (type == '4') {
                favPraise($(this), 'fav', 4);

            }
        });
    });
})
</script>
<script type="text/javascript">
$(function() {
    $('.recordbtn1').click(function(){
        $('.recordbox1').show();
    });
    $('.recordbtn2').click(function(){
        $('.recordbox2').show();
    });

    $('.imgslide').unslider({
        speed: 500,               //  The speed to animate each slide (in milliseconds)
        delay: 3000,              //  The delay between slide animations (in milliseconds)
        complete: function() {},  //  A function that gets called after every slide animation
        keys: true,               //  Enable keyboard (left, right) arrow shortcuts
        dots: true,               //  Display dot navigation
        fluid: false              //  Support responsive design. May break non-responsive designs
    });
    var unslider = $('.imgslide').unslider();
    $('.unslider-arrow').click(function() {
        var fn = this.className.split(' ')[1];
        unslider.data('unslider')[fn]();
    });
});
</script>
</body>
</html>

templates/org_detail_courses.html
{% extends 'org_base.html' %}
{% block title %}机构-课程列表{% endblock %}
{% block org_bread_path %}机构课程{% endblock %}

{% block org_right_layout %}
<div class="right companycenter layout">
    <div class="head">
        <h1>机构课程</h1>
    </div>
    <div class="brief group_list">
        {% for course in courses %}
            <div class="module1_5 box">
                <a class="comp-img-box" href="course-detail.html">
                    <img width="214" height="195" src="{{ MEDIA_URL }}{{ course.cover_img }}"/>
                </a>
                <div class="des">
                    <a href="course-detail.html"><h2>{{ course.name }}</h2></a>
                    <span class="fl">课时：<i class="key">{{ course.duration }}</i></span>
                    <span class="fr">学习人数：{{ course.stu_num }}</span>
                </div>
                <div class="bottom">
                    <span class="fl">{{ org.name }}</span>
                     <span class="star fr  notlogin
                        " data-favid="13" data-fav-type="4">
                        {{ course.fav_num }}
                    </span>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="pagination">
        <span class="step-links">
            {% if courses.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ courses.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ courses.number }} of {{ courses.paginator.num_pages }}.
            </span>

            {% if courses.has_next %}
                <a href="?page={{ courses.next_page_number }}">next</a>
                <a href="?page={{ courses.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock %}

templates/org_detail_desc.html
{% extends 'org_base.html' %}
{% block title %}机构-介绍{% endblock %}
{% block org_bread_path %}机构介绍{% endblock %}

{% block org_right_layout %}
<div class="right companycenter layout" >
    <div class="head">
        <h1>机构介绍</h1>
    </div>
    <div class="des">
        {{ org.description }}
    </div>
</div>
{% endblock %}

templates/org_detail_homepage.html
{% extends 'org_base.html' %}
{% block title %}机构首页{% endblock %}
{% block org_bread_path %}机构首页{% endblock %}

{% block org_right_layout %}
<div class="right companycenter layout grouping" >
    <div class="head">
        <h1>全部课程</h1>
        <a class="green fr more" href="org-detail-course.html">查看更多  >  </a>
    </div>
    <div class="brief group_list">
        {% for course in all_courses %}
            <div class="module1_5 box">
                <a href="course-detail.html"><img width="214" src="{{ MEDIA_URL }}{{ course.cover_img }}"/></a>
                <div class="des">
                    <a href="course-detail.html"><h2>{{ course.name }}</h2></a>
                    <span class="fl">课时：<i class="key">{{ course.duration }}</i></span>
                    <span class="fr">参加人数：{{ course.stu_num }}</span>
                </div>
                <div class="bottom">
                    <span class="fl">{{ org.name }}</span>
                     <span class="star fr  notlogin
                        " data-favid="13"  data-fav-type="4">
                        0
                    </span>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
<div class="right companycenter layout" >
    <div class="head">
    <h1>机构教师</h1>
    <a class="green fr more" href="org-detail-teachers.html">查看更多  >  </a>
    </div>

    <div class="diarys">
        {% for teacher in all_teachers %}
        <div class="module5 share company-diary-box" style="padding:10px 0;">
            <div class="left">
                <img class="pic" src="{{ MEDIA_URL }}{{ teacher.avatar }}"/>
<!--                <p>昵称：{{ teacher.name }}</p>-->
            </div>
            <div class="right">
                <div class="top">
                    <div class="fl">
                        <a href=""><h1>{{ teacher.job_title }}</h1></a>
                        <span>工作年限: {{ teacher.working_age }}</span>
                    </div>
                </div>
                <div class="middle" style="border-bottom:0;">教学特点: {{ teacher.teach_feature }}</div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div class="right companycenter layout" >
<div class="head">
<h1>机构介绍</h1>
<a class="green fr more" href="org-detail-desc.html">查看更多  >  </a>
</div>
<div class="cont">{{ org.description }}</div>
</div>
{% endblock %}

templates/org_detail_teachers.html
{% extends 'org_base.html' %}
{% block title %}机构-讲师列表{% endblock %}
{% block org_bread_path %}机构讲师{% endblock %}

{% block org_right_layout %}
<div class="right companycenter layout" >
    <div class="head">
        <h1>机构讲师</h1>
    </div>
    <div class="messagelist">
        <div class=" butler_list butler-fav-box">
            {% for teacher in teachers %}
            <dl class="des users">
                <dt>
                    <a href="">
                    <img width="100" height="100" class="scrollLoading" data-url="{{ MEDIA_URL }}{{ teacher.avatar }}" src="{{ MEDIA_URL }}{{ teacher.avatar }}"/>
                    </a>
                </dt>
                <dd>
                    <h1>
                        <a href="">{{ teacher.name }}<span class="key">已认证</span></a>
                    </h1>
                    <ul class="cont clearfix">
                        <li class="time">工作年限：<span>{{ teacher.working_age }}</span></li>
                        <li class="c7">课程数：<span>{{ teacher.courses }}</span></li>
                    </ul>
                </dd>
            </dl>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/org_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}机构列表{% endblock %}

{% block custom_bread %}
<section>
    <div class="wp">
        <ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li>课程机构</li>
        </ul>
    </div>
</section>
{% endblock %}

{% block content %}
<section>
	<div class="wp butler_list_box list">
	<div class='left'>
		<div class="listoptions">
			<ul>
				<li>
					<h2>机构类别</h2>
					<div class="cont">
                        <a href="?category=&city={{ city_id }}"><span class="{% if org_category == '' %}active2{% endif %}">全部</span></a>

                        <a href="?category=TRAINING ORGANIZATIONS&city={{ city_id }}"><span class="{% if org_category == 'TRAINING ORGANIZATIONS' %}active2{% endif %}"}>培训机构</span></a>

                        <a href="?category=COLLEGES AND UNIVERSITIES&city={{ city_id }}"><span class="{% if org_category == 'COLLEGES AND UNIVERSITIES' %}active2{% endif %}">高校</span></a>

                        <a href="?category=INDIVIDUAL&city={{ city_id }}"><span class="{% if org_category == 'INDIVIDUAL' %}active2{% endif %}">个人</span></a>

					</div>
				</li>
				<li>
					<h2>所在地区</h2>
					<div class="more">更多</div>
					<div class="cont">
                        <a href="?category={{ org_category }}&city="><span class="{% if city_id == '' %}active2{% endif %}">全部</span></a>
                        {% for city in all_cities %}
                            <a href="?city={{ city.id }}&category={{ org_category }}"><span class="{% if city_id == city.id|stringformat:'i' %}active2{% endif %}">{{ city.name }}</span></a>
                        {% endfor %}
					</div>
				</li>
			</ul>
		</div>
		<div class="all">共<span class="key">{{ org_num }}</span>家</div>
		<div class="butler_list company list">
            <div class="layout">
                <div class="head">
                    <ul class="tab_header">
                        <li class="{% if sort == '' %}active{% endif %}"><a href="?category={{ org_category }}&city={{ city_id }}">全部</a> </li>
                        <li class="{% if sort == 'students' %}active{% endif %}"><a href="?sort=students&category={{ org_category }}&city={{ city_id }}">学习人数 &#8595;</a></li>
                        <li class="{% if sort == 'courses' %}active{% endif %}"><a href="?sort=courses&category={{ org_category }}&city={{ city_id }}">课程数 &#8595;</a></li>
                    </ul>
                </div>
                {% for org in all_orgs %}
                    <dl class="des difdes">
                        <dt>
                            <a href="{% url 'org:desc' org.id %}">
                                <img width="200" height="120" class="scrollLoading" data-url="{{ MEDIA_URL }}{{ org.avatar }}"/>
                            </a>
                        </dt>
                        <dd>
                            <div class="clearfix">
                                 <a href="{% url 'org:desc' org.id %}">
                                     <h1>{{ org.name }}</h1>
                                     <div class="pic fl">
                                         {% if org.is_certified %}
                                             <img src="{% static 'images/authentication.png' %}"/>
                                         {% endif %}
                                         {% if org.is_gold %}
                                             <img src="{% static 'images/gold.png' %}"/>
                                         {% endif %}
                                     </div>
                                 </a>
                            </div>
                            <ul class="cont">
                                <li class="first"><p class="pic9">课程数：<span>{{ org.course_num }}</span></p><p class="c7">学习人数：<span>{{ org.stu_num }}</span></p></li>
                                <li class="c8" style="padding-left:18px;">
                                    {{ org.address }}</li>
                                <li class="pic10" style="padding-left:18px;">热门课程：
                                    {% for course in org.courses %}
                                        <a href="/diary/19/">{{ course.name }}</a>
                                    {% endfor %}

                                </li>
                            </ul>
                        </dd>
                        <div class="buy start_groupbuy jsShowPerfect2" data-id="22"><br/>联系<br/>服务</div>
                    </dl>
                {% endfor %}
            </div>
<!--            <div class="pageturn">-->
<!--                <ul class="pagelist">-->
<!--                    {% if all_orgs.has_previous %}-->
<!--                        <li class="long"><a href="?{{ all_orgs.previous_page_number.querystring }}">上一页</a></li>-->
<!--                    {% endif %}-->

<!--                    {% for page in all_orgs.pages %}-->
<!--                        {% if page %}-->
<!--                            {% if page == all_orgs.number %}-->
<!--                                <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>-->
<!--                            {% else %}-->
<!--                                <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>-->
<!--                            {% endif %}-->
<!--                        {% else %}-->
<!--                            <li class="none">...</li>-->
<!--                        {% endif %}-->
<!--                    {% endfor %}-->
<!--                    {% if all_orgs.has_next %}-->
<!--                        <li class="long"><a href="?{{ all_orgs.next_page_number.querystring }}">下一页</a></li>-->
<!--                    {% endif %}-->
<!--                </ul>-->
<!--            </div>-->
            <div class="pagination">
                <span class="step-links">
                    {% if all_orgs.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ all_orgs.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ all_orgs.number }} of {{ all_orgs.paginator.num_pages }}.
                    </span>

                    {% if all_orgs.has_next %}
                        <a href="?page={{ all_orgs.next_page_number }}">next</a>
                        <a href="?page={{ all_orgs.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
	</div>
	<div class="right companyright">
			<div class="head">我要学习</div>
			<form class="rightform" id="jsStayForm">
				<div>
                    <img src="{% static 'images/rightform1.png' %}"/>
                    <input type="text" name="name" id="companyName" placeholder="名字" maxlength="25" />
                </div>
				<div>
                    <img src="{% static 'images/rightform2.png' %}"/>
                    <input type="text" name="mobile" id="companyMobile" placeholder="联系电话"/>
                </div>
				<div>
                    <img src="{% static 'images/rightform3.png' %}"/>
                    <input type="text" name="course_name" id="companyAddress" placeholder="课程名" maxlength="50" />
                </div>
                <p class="error company-tips" id="jsCompanyTips"></p>
				<input class="btn" type="text" id="jsStayBtn" value="立即咨询 >" />
            </form>
		</div>

		<div class="right companyrank layout">
			<div class="head">授课机构排名</div>
                {% for org in hot_orgs %}
                    <dl class="des">
                        <dt class="num fl">{{ forloop.counter }}</dt>
                        <dd>
                            <a href="/company/2/"><h1>{{ org.name }}</h1></a>
                            <p>{{ org.address }}</p>
                        </dd>
                    </dl>
                {% endfor %}
		</div>
        </div>
</section>
{% endblock %}

{% block custom_js %}
<script>
    $(function(){
        $(document).ready(function() {
            $('#jsStayBtn').on('click', function () {
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "/org/add_ask/",
                    data: $('#jsStayForm').serialize(),
                    async: true,
                    success: function (data) {
                        if (data.status == 'success') {
                            $('#jsStayForm')[0].reset();
                            $('#jsCompanyTips').html("");
                            alert("提交成功")
                        } else if (data.status == 'fail') {
                            $('#jsCompanyTips').html(data.msg)
                        }
                    },
                });
            });
        });
    })

</script>
{% endblock %}