apps/courses/urls.py
from django.urls import path

from apps.courses import views


urlpatterns = [
    path('', views.CourseIndexView.as_view(), name='list'),
    path('<int:pk>/', views.CourseDetailView.as_view(), name='detail'),
    path('<int:course_id>/learn', views.CourseStudyView.as_view(),
         name='learn'),
]

edu_online/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, re_path
from django.views.generic import TemplateView
from django.views.static import serve

from apps.users.views import LoginView, LogoutView
from edu_online.settings import MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('captcha/', include('captcha.urls')),
    path('org/', include(('apps.organizations.urls', 'organizations'),
                         namespace='org')),
    path('op/', include(('apps.operations.urls', 'operations'),
                        namespace='op')),
    path('course/', include(('apps.courses.urls', 'courses'),
                            namespace='course')),
    # 配置上传文件的访问url
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
]

apps/courses/models.py
from django.db import models

from apps.users.models import BaseModel


class Course(BaseModel):
    LEVEL_CHOICE = [
        ('L', 'LOW'),
        ('M', 'MIDDLE'),
        ('H', 'HIGH')
    ]

    teacher = models.ForeignKey('organizations.teacher',
                                on_delete=models.CASCADE)
    #org = models.ForeignKey('organizations.org', on_delete=models.CASCADE)
    name = models.CharField(max_length=50, verbose_name='course name')
    description = models.CharField(max_length=255,
                                   verbose_name='course description')
    level = models.CharField(choices=LEVEL_CHOICE, max_length=1,
                             verbose_name='course level')
    stu_num = models.PositiveIntegerField(
        default=0,
        verbose_name='number of students of the course')
    duration = models.PositiveIntegerField(default=0,
                                           verbose_name='Course duration')
    fav_num = models.PositiveIntegerField(
        default=0,
        verbose_name='number of favorite of the course')
    view_num = models.PositiveIntegerField(
        default=0,
        verbose_name='number of views of the course')
    category = models.CharField(max_length=50, null=True, blank=True,
                                verbose_name='course category')
    course_note = models.CharField(max_length=255, null=True, blank=True,
                                   verbose_name='course note')
    teacher_comment = models.CharField(max_length=255, null=True, blank=True,
                                       verbose_name='teacher comment')
    detail = models.TextField(verbose_name='Course detail')
    cover_img = models.ImageField(upload_to="courses/%Y/%m",
                                  default="default.jpeg",
                                  max_length=100,
                                  verbose_name='cover of the course')

    class Meta:
        verbose_name = 'course'
        verbose_name_plural = 'courses'

    def __str__(self):
        return self.name

    @property
    def chapter_count(self):
        return self.chapter_set.count()


class Chapter(BaseModel):
    course = models.ForeignKey('Course', on_delete=models.CASCADE,
                               verbose_name='course')
    name = models.CharField(max_length=30, verbose_name='chapter name')
    duration = models.PositiveIntegerField(default=0,
                                           verbose_name='chapter duration')

    class Meta:
        verbose_name = 'chapter'
        verbose_name_plural = 'chapters'

    def __str__(self):
        return self.name


class Section(BaseModel):
    chapter = models.ForeignKey('Chapter', on_delete=models.CASCADE,
                                verbose_name='chapter')
    name = models.CharField(max_length=30, verbose_name='section name')
    duration = models.PositiveIntegerField(default=0,
                                           verbose_name='section duration')
    url = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'section'
        verbose_name_plural = 'sections'

    def __str__(self):
        return self.name


class CourseResource(BaseModel):
    course = models.ForeignKey('Course', on_delete=models.CASCADE,
                               verbose_name='course')
    name = models.CharField(max_length=30, verbose_name='Resource name')
    file = models.FileField(upload_to='courses/resources/%Y/%m',
                            verbose_name='resource file')

    class Meta:
        verbose_name = 'course resource'
        verbose_name_plural = 'course resources'

    def __str__(self):
        return self.name


class Tag(BaseModel):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class CourseTag(BaseModel):
    course = models.ForeignKey('Course', on_delete=models.CASCADE)
    tag = models.ForeignKey('Tag', on_delete=models.CASCADE)

    class Meta:
        unique_together = ('course', 'tag')

apps/courses/views.py
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import connection
from django.shortcuts import get_object_or_404, render
from django.views.generic import DetailView, ListView, View

from apps.courses.models import Course, CourseResource, CourseTag
from apps.operations.models import UserFavorite


logger = logging.getLogger(__name__)


def be_favorite(user_id, fav_id, fav_type):
    return UserFavorite.objects.filter(user=user_id,
                                       fav_id=fav_id,
                                       fav_type=fav_type)


class CourseIndexView(ListView):
    template_name = 'courses/courses_list.html'
    context_object_name = 'all_courses'
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CourseIndexView, self).get_context_data()
        sort_type = self.request.GET.get('sort', '')
        context['sort_type'] = sort_type
        return context

    def get_queryset(self):
        sort_type = self.request.GET.get('sort', '')
        if sort_type == 'hot':
            ordering = '-fav_num'
        elif sort_type == 'students':
            ordering = '-stu_num'
        else:
            ordering = '-created_at'
        return Course.objects.order_by(ordering)


class CourseDetailView(DetailView):
    model = Course
    template_name = 'courses/course_detail.html'

    def _get_related_courses(self):
        course_id = self.object.id
        tags = CourseTag.objects.filter(course=course_id).values('tag')
        tags_list = [tag['tag'] for tag in tags]
        courses = CourseTag.objects.filter(
            tag__in=tags_list).exclude(
            course=course_id).select_related('course')
        results = [i.course for i in list(set(courses))]
        # logger.warning('[+++++++++++]')
        # for query in connection.queries:
        #     logger.warning(query['sql'])
        #     logger.warning('----------')
        # logger.warning('[+++++++++++]')
        return results

    def get_context_data(self, **kwargs):
        context = super(CourseDetailView, self).get_context_data()
        if not self.request.user.is_authenticated:
            return context
        course_fav_record = be_favorite(self.request.user, self.object.id, 1)
        course_favorite = True if course_fav_record else False
        org_fav_record = be_favorite(self.request.user,
                                     self.object.teacher.org.id,
                                     3)
        org_favorite = True if org_fav_record else False
        context['course_favorite'] = course_favorite
        context['org_favorite'] = org_favorite
        context['related_courses'] = self._get_related_courses()[0:3]
        return context


class CourseStudyView(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'next'

    def get(self, request, course_id):
        course = get_object_or_404(Course, pk=course_id)
        course_recourses = CourseResource.objects.filter(
            course=course_id).values('name', 'file')
        return render(request, 'courses/course_study.html',
                      context={'course': course,
                               'course_recourses': course_recourses})

templates/courses/course_section.html
{% extends 'base.html' %}
{% load static %}
{% block title %}课程章节信息{% endblock %}

{% block custom_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/aui.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
{% endblock %}

{% block custom_bread %}
<section>
    <div class="wp">
        <ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li><a href="{% url 'course:list' %}">所有课程</a>></li>
            <li><a href="{% url 'course:detail' course.id %}">课程详情</a>></li>
            <li>章节信息</li>
        </ul>
    </div>
</section>
{% endblock %}

{% block content %}
<div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta">难度</span>
                    <span class="meta-value"><strong>{{ course.get_level_display }}</strong></span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta">时长</span>
                    <span class="meta-value"><strong>{{ course.duration }}分钟</strong></span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta">学习人数</span>
                    <span class="meta-value"><strong>{{ course.stu_num }}</strong></span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
        <div class="content-wrap clearfix">
            <div class="content">
                <div class="mod-tab-menu">
                    <ul class="course-menu clearfix">
                        <li><a class="ui-tabs-active active" id="learnOn"  href="course-video.html"><span>章节</span></a></li>
                        <li><a id="commentOn" class="" href="course-comment.html"><span>评论</span></a></li>
                    </ul>
                </div>
<!--                <div id="notice" class="clearfix">-->
<!--                    <div class="l"> <strong>课程公告:</strong> <a  href="javascript:void(0)">Spring的文档以及相关的jar文件已上传</a> </div>-->
<!--                </div>-->

                <div class="mod-chapters">
                    {% for chapter in course.chapter_set.all %}
                        <div class="chapter chapter-active" >
                            <h3>
                                <strong><i class="state-expand"></i>{{ chapter.name }}</strong>
                            </h3>
                            <ul class="video">
                                {% for section in chapter.section_set.all %}
                                    <li>
                                        <a target="_blank" href='/video/3662' class="J-media-item studyvideo">{{ section.name }}({{ section.duration }}分钟)
                                            <i class="study-state"></i>
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endfor %}
                </div>

            </div>
            <div class="aside r">
                <div class="bd">

                    <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">

                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;前端页面</span>
                                <a href="../media/course/resource/2016/11/media.zip" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>

                        </ul>
                    </div>
                    <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="/u/315464/courses?sort=publish" target="_blank">
                                <img src='{{ course.teacher.avatar.url }}' width='80' height='80' />
                            </a>
                            <span class="tit">
                              <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
                            </span>
                            <span class="job">{{ course.teacher.job_title }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.course_note }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.teacher_comment }}</dd>
                            </dl>
                        </div>
                    </div>


                    <div class="cp-other-learned  js-comp-tabs">
                        <div class="cp-header clearfix">
                            <h2 class="cp-tit l">该课的同学还学过</h2>
                        </div>
                        <div class="cp-body">
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                <!-- img 200 x 112 -->
                                <ul class="other-list">

                                    <li class="curr">
                                        <a href="course-detail.html" target="_blank">
                                            <img src="../media/courses/2016/11/540e57300001d6d906000338-240-135_n0L8vbw.jpg" alt="django与vuejs实战项目2">
                                            <span class="name autowrap">django与vuejs实战项目2</span>
                                        </a>
                                    </li>

                                    <li class="curr">
                                        <a href="course-detail.html" target="_blank">
                                            <img src="../media/courses/2016/12/python面向对象.jpg" alt="python面向对象">
                                            <span class="name autowrap">python面向对象</span>
                                        </a>
                                    </li>

                                    <li class="curr">
                                        <a href="course-detail.html" target="_blank">
                                            <img src="../media/courses/2016/12/python文件处理.jpg" alt="python文件处理">
                                            <span class="name autowrap">python文件处理</span>
                                        </a>
                                    </li>

                                    <li class="curr">
                                        <a href="course-detail.html" target="_blank">
                                            <img src="../media/courses/2016/11/mysql.jpg" alt="django入门">
                                            <span class="name autowrap">django入门</span>
                                        </a>
                                    </li>

                                    <li class="curr">
                                        <a href="course-detail.html" target="_blank">
                                            <img src="../media/courses/2016/12/mysql.jpg" alt="xadmin进阶开发">
                                            <span class="name autowrap">xadmin进阶开发</span>
                                        </a>
                                    </li>

                                </ul>
                            </div>
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                <ul class="other-list">
                                    <li class="curr">
                                        <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                            <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg" alt="Java工程师">
                                            <span class="name autowrap">Java工程师</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                </div>    </div>
        </div>
        <div class="clear"></div>

    </div>

</div>
</div>
{% endblock %}

templates/courses/course_study.html
{% extends 'base.html' %}
{% load static %}
{% block title %}课程章节信息{% endblock %}

{% block custom_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/aui.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
{% endblock %}

{% block custom_bread %}
<section>
    <div class="wp">
        <ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li><a href="{% url 'course:list' %}">所有课程</a>></li>
            <li><a href="{% url 'course:detail' course.id %}">课程详情</a>></li>
            <li>章节信息</li>
        </ul>
    </div>
</section>
{% endblock %}

{% block content %}
<div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta">难度</span>
                    <span class="meta-value"><strong>{{ course.get_level_display }}</strong></span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta">时长</span>
                    <span class="meta-value"><strong>{{ course.duration }}分钟</strong></span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta">学习人数</span>
                    <span class="meta-value"><strong>{{ course.stu_num }}</strong></span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
        <div class="content-wrap clearfix">
            <div class="content">
                <div class="mod-tab-menu">
                    <ul class="course-menu clearfix">
                        <li><a class="ui-tabs-active active" id="learnOn"  href="course-video.html"><span>章节</span></a></li>
                        <li><a id="commentOn" class="" href="course-comment.html"><span>评论</span></a></li>
                    </ul>
                </div>
<!--                <div id="notice" class="clearfix">-->
<!--                    <div class="l"> <strong>课程公告:</strong> <a  href="javascript:void(0)">Spring的文档以及相关的jar文件已上传</a> </div>-->
<!--                </div>-->

                <div class="mod-chapters">
                    {% for chapter in course.chapter_set.all %}
                        <div class="chapter chapter-active" >
                            <h3>
                                <strong><i class="state-expand"></i>{{ chapter.name }}</strong>
                            </h3>
                            <ul class="video">
                                {% for section in chapter.section_set.all %}
                                    <li>
                                        <a target="_blank" href='/video/3662' class="J-media-item studyvideo">{{ section.name }}({{ section.duration }}分钟)
                                            <i class="study-state"></i>
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endfor %}
                </div>

            </div>
            <div class="aside r">
                <div class="bd">
                    <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                            {% for resource in course_recourses %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ resource.name }}</span>
                                <a href="{{ MEDIA_URL }}{{ resource.file }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="/u/315464/courses?sort=publish" target="_blank">
                                <img src='{{ course.teacher.avatar.url }}' width='80' height='80' />
                            </a>
                            <span class="tit">
                              <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
                            </span>
                            <span class="job">{{ course.teacher.job_title }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.course_note }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.teacher_comment }}</dd>
                            </dl>
                        </div>
                    </div>


                    <div class="cp-other-learned  js-comp-tabs">
                        <div class="cp-header clearfix">
                            <h2 class="cp-tit l">该课的同学还学过</h2>
                        </div>
                        <div class="cp-body">
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                <!-- img 200 x 112 -->
                                <ul class="other-list">

                                    <li class="curr">
                                        <a href="course-detail.html" target="_blank">
                                            <img src="../media/courses/2016/11/540e57300001d6d906000338-240-135_n0L8vbw.jpg" alt="django与vuejs实战项目2">
                                            <span class="name autowrap">django与vuejs实战项目2</span>
                                        </a>
                                    </li>

                                    <li class="curr">
                                        <a href="course-detail.html" target="_blank">
                                            <img src="../media/courses/2016/12/python面向对象.jpg" alt="python面向对象">
                                            <span class="name autowrap">python面向对象</span>
                                        </a>
                                    </li>

                                    <li class="curr">
                                        <a href="course-detail.html" target="_blank">
                                            <img src="../media/courses/2016/12/python文件处理.jpg" alt="python文件处理">
                                            <span class="name autowrap">python文件处理</span>
                                        </a>
                                    </li>

                                    <li class="curr">
                                        <a href="course-detail.html" target="_blank">
                                            <img src="../media/courses/2016/11/mysql.jpg" alt="django入门">
                                            <span class="name autowrap">django入门</span>
                                        </a>
                                    </li>

                                    <li class="curr">
                                        <a href="course-detail.html" target="_blank">
                                            <img src="../media/courses/2016/12/mysql.jpg" alt="xadmin进阶开发">
                                            <span class="name autowrap">xadmin进阶开发</span>
                                        </a>
                                    </li>

                                </ul>
                            </div>
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                <ul class="other-list">
                                    <li class="curr">
                                        <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                            <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg" alt="Java工程师">
                                            <span class="name autowrap">Java工程师</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                </div>    </div>
        </div>
        <div class="clear"></div>

    </div>

</div>
</div>
{% endblock %}

templates/courses/courses_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}所有课程列表{% endblock %}
{% block custom_bread %}
<section>
    <div class="wp">
        <ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li>所有课程</li>
        </ul>
    </div>
</section>
{% endblock %}

{% block content %}
<section>
	<div class="wp">
		<div class="list" style="margin-top:0;">
			<div class="layout">
				<div class="head">
					<ul class="tab_header">
						<li class="{% if sort_type == '' %}active{% endif %}"><a href="?sort=">最新发布 </a></li>
						<li class="{% if sort_type == 'hot' %}active{% endif %}"><a href="?sort=hot">最多收藏</a></li>
						<li class="{% if sort_type == 'students' %}active{% endif %}"><a href="?sort=students">学习人数</a></li>
					</ul>
				</div>
                <div id="inWindow">
                    <div class="tab_cont " id="content">
					    <div class="group_list">
							{% for course in page_obj %}
								<div class="box">
									<a href="{% url 'course:detail' course.id %}">
										<img width="280" height="350" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.cover_img }}"/>
									</a>
									<div class="des">
										<a href="{% url 'course:detail' course.id %}">
											<h2>{{ course.name }}</h2>
										</a>
										<span class="fl">时长：<i class="key">{{ course.duration }}分钟</i></span>
										<span class="fr">学习人数：{{ course.stu_num }}&nbsp;</span>
									</div>
									<div class="bottom">
										<a href="course-detail.html"><span class="fl">来自{{ course.teacher.org.name }}</span></a>
										<span class="star fr  notlogin
											" data-favid="15">
											{{ course.fav_num }}
										</span>
									</div>
								</div>
							{% endfor %}
					    </div>
						<div class="pagination">
							<span class="step-links">
								{% if page_obj.has_previous %}
									<a href="?sort={{ sort_type }}&page=1">&laquo; first</a>
									<a href="?sort={{ sort_type }}&page={{ page_obj.previous_page_number }}">previous</a>
								{% endif %}

								<span class="current">
									Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
								</span>

								{% if page_obj.has_next %}
									<a href="?sort={{ sort_type }}&page={{ page_obj.next_page_number }}">next</a>
									<a href="?sort={{ sort_type }}&page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
								{% endif %}
							</span>
						</div>
				    </div>
                </div>
			</div>
<!--			<div class="right layout">-->
<!--				<div class="head">热门课程推荐</div>-->
<!--				<div class="group_recommend">-->

<!--                    <dl>-->
<!--						<dt>-->
<!--							<a target="_blank" href="">-->
<!--								<img width="240" height="220" class="scrollLoading" src="../media/courses/2016/11/540e57300001d6d906000338-240-135_n0L8vbw.jpg"/>-->
<!--							</a>-->
<!--						</dt>-->
<!--						<dd>-->
<!--							<a target="_blank" href=""><h2> django与vuejs实战项目2</h2></a>-->
<!--							<span class="fl">难度：<i class="key">高级</i></span>-->
<!--						</dd>-->
<!--					</dl>-->

<!--                    <dl>-->
<!--						<dt>-->
<!--							<a target="_blank" href="">-->
<!--								<img width="240" height="220" class="scrollLoading" src="../media/courses/2016/12/python面向对象.jpg"/>-->
<!--							</a>-->
<!--						</dt>-->
<!--						<dd>-->
<!--							<a target="_blank" href=""><h2> python面向对象</h2></a>-->
<!--							<span class="fl">难度：<i class="key">中级</i></span>-->
<!--						</dd>-->
<!--					</dl>-->

<!--                    <dl>-->
<!--						<dt>-->
<!--							<a target="_blank" href="">-->
<!--								<img width="240" height="220" class="scrollLoading" src="../media/courses/2016/12/python文件处理.jpg"/>-->
<!--							</a>-->
<!--						</dt>-->
<!--						<dd>-->
<!--							<a target="_blank" href=""><h2> python文件处理</h2></a>-->
<!--							<span class="fl">难度：<i class="key">中级</i></span>-->
<!--						</dd>-->
<!--					</dl>-->

<!--				</div>-->
<!--			</div>-->
		</div>
    </div>
</section>
{% endblock %}